# Services for local development

version: "3.0"
services:
  database:
    image: amsterdam/postgres11
    ports:
      - "5403:5432"
    environment:
      POSTGRES_PASSWORD: insecure
      # used by apache to allow complete access for dev envs
      LOCAL: t
    volumes:
        - "~/.ssh/datapunt.key:/root/.ssh/datapunt.key"

  map:
    build:
      context: .
    ports:
      - "8383:80"
    links:
      - "database:database"
    environment:
      # Uncomment the following line to have private maps served
      ACCESS_SCOPE: private 
      BAG_V11_DB_NAME: bag_v11
      BAG_V11_DB_USER: postgres
      BAG_V11_DB_PASSWORD: insecure
      BAG_V11_DB_HOST: database

      NAP_DB_NAME: nap
      NAP_DB_USER: postgres
      NAP_DB_PASSWORD: insecure
      NAP_DB_HOST: database

      MILIEUTHEMAS_DB_NAME: milieuthemas
      MILIEUTHEMAS_DB_USER: postgres
      MILIEUTHEMAS_DB_PASSWORD: insecure
      MILIEUTHEMAS_DB_HOST: database

      PANORAMA_DB_NAME: panorama
      PANORAMA_DB_USER: postgres
      PANORAMA_DB_PASSWORD: insecure
      PANORAMA_DB_HOST: database

      BASISKAART_DB_NAME: basiskaart
      BASISKAART_DB_USER: postgres
      BASISKAART_DB_PASSWORD: insecure
      BASISKAART_DB_HOST: database

      HANDELSREGISTER_DB_NAME: handelsregister
      HANDELSREGISTER_DB_USER: postgres
      HANDELSREGISTER_DB_PASSWORD: insecure
      HANDELSREGISTER_DB_HOST: database

      MONUMENTEN_DB_NAME: monumenten
      MONUMENTEN_DB_USER: postgres
      MONUMENTEN_DB_PASSWORD: insecure
      MONUMENTEN_DB_HOST: database

      DATASELECTIE_DB_NAME: dataselectie
      DATASELECTIE_DB_USER: postgres
      DATASELECTIE_DB_PASSWORD: insecure
      DATASELECTIE_DB_HOST: database

      VARIOUS_SMALL_DATASETS_DB_NAME: various_small_datasets
      VARIOUS_SMALL_DATASETS_DB_USER: various_small_datasets
      VARIOUS_SMALL_DATASETS_DB_PASSWORD: insecure
      VARIOUS_SMALL_DATASETS_DB_HOST: database

      DATASERVICES_DB_NAME: dataservices
      DATASERVICES_DB_USER: dataservices
      DATASERVICES_DB_PASSWORD: insecure
      DATASERVICES_DB_HOST: database