ARG BASE_IMAGE

FROM ${BASE_IMAGE}

USER root
# Copy referentiekaarten mapfiles into the root dir so they will be served

RUN rm -rf /srv/mapserver/private
COPY --chown=999:999 /referentiekaarten/ /srv/mapserver/
USER www-data
