# This file is only for local development purposes. The actual deployment
# configuration lives in a separate repository.

version: "3.0"

services:
  database:
    build:
      context: .
      dockerfile: Dockerfile.database
    ports:
      - "5403:5432"
    environment:
      - POSTGRES_PASSWORD=insecure
    command: ["postgres", "-c", "log_statement=all"]

  proxy:
    build:
      context: jwtproxy
      dockerfile: Dockerfile.dev
    ports:
      - 9191:8000
    volumes:
      - ./jwtproxy/src:/app/jwtproxy
    environment:
      PROXY_URL: http://map
      JWKS_PATH: /app/jwtproxy/test_jwk.json
      LOG_LEVEL: DEBUG
      #JWKS_URL: "https://iam.amsterdam.nl/auth/realms/datapunt-ad-acc/protocol/openid-connect/certs"

  # Bare bones 'webserver' to behave as public loadbalancer
  publicdummy:
    image: python:3.11-slim-bullseye
    ports:
      - 8000:8000
    command: python3 -m http.server 8000

  map:
    build:
      context: .
    ports:
      - "8383:80"
    environment:
      # Uncomment the following line to have private maps served
      ACCESS_SCOPE: private 
      # Used by apache to allow complete access for local dev
      LOCAL: "true"
      BAG_V11_DB_NAME: bag_v11
      BAG_V11_DB_USER: postgres
      BAG_V11_DB_PASSWORD: insecure
      BAG_V11_DB_HOST: database

      PANORAMA_DB_NAME: panorama
      PANORAMA_DB_USER: postgres
      PANORAMA_DB_PASSWORD: insecure
      PANORAMA_DB_HOST: database

      BASISKAART_DB_NAME: basiskaart
      BASISKAART_DB_USER: postgres
      BASISKAART_DB_PASSWORD: insecure
      BASISKAART_DB_HOST: database

      HANDELSREGISTER_DB_NAME: handelsregister
      HANDELSREGISTER_DB_USER: postgres
      HANDELSREGISTER_DB_PASSWORD: insecure
      HANDELSREGISTER_DB_HOST: database

      DATASELECTIE_DB_NAME: dataselectie
      DATASELECTIE_DB_USER: postgres
      DATASELECTIE_DB_PASSWORD: insecure
      DATASELECTIE_DB_HOST: database

      DATASERVICES_DB_NAME: dataservices
      DATASERVICES_DB_USER: postgres
      DATASERVICES_DB_PASSWORD: insecure
      DATASERVICES_DB_HOST: database

      MAP_URL: "http://map"
      LEGEND_URL: "http://map"
