database:
  image: admin.datapunt.amsterdam.nl:5000/atlas/postgres
  ports:
    - "5403:5432"
  environment:
    POSTGRES_PASSWORD: insecure

map:
  build: .
  ports:
    - "8989:80"
  links:
    - "database:atlas_db"
    - "database:nap_db"
    - "database:milieu_db"
  environment:
    ATLAS_DB_NAME: atlas
    ATLAS_DB_USER: postgres
    ATLAS_DB_PASSWORD: insecure
    NAP_DB_NAME: nap
    NAP_DB_USER: postgres
    NAP_DB_PASSWORD: insecure
    MILIEU_DB_NAME: postgres
    MILIEU_DB_USER: postgres
    MILIEU_DB_PASSWORD: insecure
