version: "3.0"
services:
  database:
    image: amsterdam/postgres11
    ports:
      - "5403:5432"
    environment:
      POSTGRES_PASSWORD: insecure
    volumes:
        - "~/.ssh/datapunt.key:/root/.ssh/datapunt.key"

  map:
    build:
      context: .
      dockerfile: Dockerfile_noproxy_tiles
    ports:
      - "8001:80"
    links:
      - "database:database"
    environment:
      BAG_DB_NAME: bag
      BAG_DB_USER: postgres
      BAG_DB_PASSWORD: insecure
      BAG_DB_HOST: database

      NAP_DB_NAME: nap
      NAP_DB_USER: postgres
      NAP_DB_PASSWORD: insecure
      NAP_DB_HOST: database

      MILIEUTHEMAS_DB_NAME: milieuthemas
      MILIEUTHEMAS_DB_USER: postgres
      MILIEUTHEMAS_DB_PASSWORD: insecure
      MILIEUTHEMAS_DB_HOST: database

      PANORAMA_DB_NAME: panorama
      PANORAMA_DB_USER: postgres
      PANORAMA_DB_PASSWORD: insecure
      PANORAMA_DB_HOST: database

      PARKEERVAKKEN_DB_NAME: parkeervakken
      PARKEERVAKKEN_DB_USER: postgres
      PARKEERVAKKEN_DB_PASSWORD: insecure
      PARKEERVAKKEN_DB_HOST: database

      PREDICTIVEPARKING_DB_NAME: predictiveparking
      PREDICTIVEPARKING_DB_USER: postgres
      PREDICTIVEPARKING_DB_PASSWORD: insecure
      PREDICTIVEPARKING_DB_HOST: database

      BASISKAART_DB_NAME: basiskaart
      BASISKAART_DB_USER: postgres
      BASISKAART_DB_PASSWORD: insecure
      BASISKAART_DB_HOST: database

      HANDELSREGISTER_DB_NAME: handelsregister
      HANDELSREGISTER_DB_USER: postgres
      HANDELSREGISTER_DB_PASSWORD: insecure
      HANDELSREGISTER_DB_HOST: database

      TELLUS_DB_NAME: tellus
      TELLUS_DB_USER: postgres
      TELLUS_DB_PASSWORD: insecure
      TELLUS_DB_HOST: database

      MONUMENTEN_DB_NAME: monumenten
      MONUMENTEN_DB_USER: postgres
      MONUMENTEN_DB_PASSWORD: insecure
      MONUMENTEN_DB_HOST: database

      OVERLASTGEBIEDEN_DB_NAME: overlastgebieden
      OVERLASTGEBIEDEN_DB_USER: postgres
      OVERLASTGEBIEDEN_DB_PASSWORD: insecure
      OVERLASTGEBIEDEN_DB_HOST: database

      GRONDEXPLOITATIE_DB_NAME: reistijdenauto
      GRONDEXPLOITATIE_DB_USER: postgres
      GRONDEXPLOITATIE_DB_PASSWORD: insecure
      GRONDEXPLOITATIE_DB_HOST: database

      DATASELECTIE_DB_NAME: dataselectie
      DATASELECTIE_DB_USER: postgres
      DATASELECTIE_DB_PASSWORD: insecure
      DATASELECTIE_DB_HOST: database

      EXTERNALDATA_DB_HOST: database
      EXTERNALDATA_DB_NAME: externaldata
      EXTERNALDATA_DB_USER: externaldata
      EXTERNALDATA_DB_PASSWORD: insecure

      MAP_URL: "http://mapserver"
      LEGEND_URL: "http://mapserver"

    volumes:
      - /tmp/srv/lufo:/srv/lufo
