FROM python:3.10-slim-bullseye

COPY supervisord.conf /etc

WORKDIR /app
COPY src ./
COPY requirements.txt .

RUN usermod --non-unique --uid 999 proxy
RUN groupmod -o -g 999 proxy
RUN chown -R 999:999 /app

RUN pip install supervisor
RUN pip install -r requirements.txt

EXPOSE 8000

USER proxy
ENTRYPOINT [ "/bin/sh", "-c", "/usr/local/bin/supervisord -n"]
