# Dockerfile for local testing of the Nginx -> aiohttp -> mapserver request flow
# Note that the configuration of the Nginx instances deployed by the controller in k8s
# will differ significantly from the config used here.

# For testing against the nginx-controller locally. A minikube setup can be used
# in combination with manifest.yml

FROM python:3.10-slim-bullseye

RUN apt-get update && apt-get install nginx -y
COPY supervisord.conf /etc

WORKDIR /app
COPY src jwtproxy
COPY nginx/nginx.conf /etc/nginx/nginx.conf
COPY nginx/server.conf /etc/nginx/conf.d/server.conf
COPY requirements_dev.txt .

RUN pip install supervisor
RUN pip install -r requirements_dev.txt

ENTRYPOINT [ "/bin/sh", "-c", "nginx -g 'daemon on;'; adev runserver /app/jwtproxy/server.py -p 8081 --app-factory main;"]