FROM python:3.10-slim-bullseye

WORKDIR /app
COPY . jwtproxy 

RUN pip install -r jwtproxy/requirements_dev.txt
EXPOSE 8000

ENTRYPOINT [ "adev", "runserver", "/app/jwtproxy/server.py", "--app-factory", "main"]