#!/usr/bin/env bash

set -e
set -u

ATLAS_DB_HOST=${ATLAS_DB_HOST:-atlas-read.service.consul}
ATLAS_DB_PORT=${ATLAS_DB_PORT:-5432}
ATLAS_DB_NAME=${ATLAS_DB_NAME:-atlas}
ATLAS_DB_USER=${ATLAS_DB_USER:-${ATLAS_DB_NAME}}
ATLAS_DB_PASSWORD=${ATLAS_DB_PASSWORD:-insecure}

NAP_DB_HOST=${NAP_DB_HOST:-nap-read.service.consul}
NAP_DB_PORT=${NAP_DB_PORT:-5432}
NAP_DB_NAME=${NAP_DB_NAME:-nap}
NAP_DB_USER=${NAP_DB_USER:-${NAP_DB_NAME}}
NAP_DB_PASSWORD=${NAP_DB_PASSWORD:-insecure}

MILIEUTHEMAS_DB_HOST=${MILIEUTHEMAS_DB_HOST:-milieuthemas-read.service.consul}
MILIEUTHEMAS_DB_PORT=${MILIEUTHEMAS_DB_PORT:-5432}
MILIEUTHEMAS_DB_NAME=${MILIEUTHEMAS_DB_NAME:-milieuthemas}
MILIEUTHEMAS_DB_USER=${MILIEUTHEMAS_DB_USER:-${MILIEUTHEMAS_DB_NAME}}
MILIEUTHEMAS_DB_PASSWORD=${MILIEUTHEMAS_DB_PASSWORD:-insecure}

PANORAMA_DB_HOST=${PANORAMA_DB_HOST:-panorama-read.service.consul}
PANORAMA_DB_PORT=${PANORAMA_DB_PORT:-5432}
PANORAMA_DB_NAME=${PANORAMA_DB_NAME:-panorama}
PANORAMA_DB_USER=${PANORAMA_DB_USER:-${PANORAMA_DB_NAME}}
PANORAMA_DB_PASSWORD=${PANORAMA_DB_PASSWORD:-insecure}

PARKEERVAKKEN_DB_HOST=${PARKEERVAKKEN_DB_HOST:-parkeervakken-read.service.consul}
PARKEERVAKKEN_DB_PORT=${PARKEERVAKKEN_DB_PORT:-5432}
PARKEERVAKKEN_DB_NAME=${PARKEERVAKKEN_DB_NAME:-parkeervakken}
PARKEERVAKKEN_DB_USER=${PARKEERVAKKEN_DB_USER:-${PARKEERVAKKEN_DB_NAME}}
PARKEERVAKKEN_DB_PASSWORD=${PARKEERVAKKEN_DB_PASSWORD:-insecure}

PREDICTIVEPARKING_DB_HOST=${PREDICTIVEPARKING_DB_HOST:-predictiveparking-read.service.consul}
PREDICTIVEPARKING_DB_PORT=${PREDICTIVEPARKING_DB_PORT:-5432}
PREDICTIVEPARKING_DB_NAME=${PREDICTIVEPARKING_DB_NAME:-predictiveparking}
PREDICTIVEPARKING_DB_USER=${PREDICTIVEPARKING_DB_USER:-${PREDICTIVEPARKING_DB_NAME}}
PREDICTIVEPARKING_DB_PASSWORD=${PREDICTIVEPARKING_DB_PASSWORD:-insecure}

BASISKAART_DB_HOST=${BASISKAART_DB_HOST:-basiskaart-read.service.consul}
BASISKAART_DB_PORT=${BASISKAART_DB_PORT:-5432}
BASISKAART_DB_NAME=${BASISKAART_DB_NAME:-basiskaart}
BASISKAART_DB_USER=${BASISKAART_DB_USER:-${BASISKAART_DB_NAME}}
BASISKAART_DB_PASSWORD=${BASISKAART_DB_PASSWORD:-insecure}

HANDELSREGISTER_DB_HOST=${HANDELSREGISTER_DB_HOST:-handelsregister-read.service.consul}
HANDELSREGISTER_DB_PORT=${HANDELSREGISTER_DB_PORT:-5432}
HANDELSREGISTER_DB_NAME=${HANDELSREGISTER_DB_NAME:-handelsregister}
HANDELSREGISTER_DB_USER=${HANDELSREGISTER_DB_USER:-${HANDELSREGISTER_DB_NAME}}
HANDELSREGISTER_DB_PASSWORD=${HANDELSREGISTER_DB_PASSWORD:-insecure}

TELLUS_DB_HOST=${TELLUS_DB_HOST:-tellus-read.service.consul}
TELLUS_DB_PORT=${TELLUS_DB_PORT:-5432}
TELLUS_DB_NAME=${TELLUS_DB_NAME:-tellus}
TELLUS_DB_USER=${TELLUS_DB_USER:-${TELLUS_DB_NAME}}
TELLUS_DB_PASSWORD=${TELLUS_DB_PASSWORD:-insecure}

MONUMENTEN_DB_HOST=${MONUMENTEN_DB_HOST:-monumenten-read.service.consul}
MONUMENTEN_DB_PORT=${MONUMENTEN_DB_PORT:-5432}
MONUMENTEN_DB_NAME=${MONUMENTEN_DB_NAME:-monumenten}
MONUMENTEN_DB_USER=${MONUMENTEN_DB_USER:-${MONUMENTEN_DB_NAME}}
MONUMENTEN_DB_PASSWORD=${MONUMENTEN_DB_PASSWORD:-insecure}

OVERLASTGEBIEDEN_DB_HOST=${OVERLASTGEBIEDEN_DB_HOST:-overlastgebieden-read.service.consul}
OVERLASTGEBIEDEN_DB_PORT=${OVERLASTGEBIEDEN_DB_PORT:-5432}
OVERLASTGEBIEDEN_DB_NAME=${OVERLASTGEBIEDEN_DB_NAME:-overlastgebieden}
OVERLASTGEBIEDEN_DB_USER=${OVERLASTGEBIEDEN_DB_USER:-${OVERLASTGEBIEDEN_DB_NAME}}
OVERLASTGEBIEDEN_DB_PASSWORD=${OVERLASTGEBIEDEN_DB_PASSWORD:-insecure}


echo Creating configuration files

cat > /srv/mapserver/connection.inc <<EOF
CONNECTIONTYPE postgis
CONNECTION "host=${ATLAS_DB_HOST} dbname=${ATLAS_DB_NAME} user=${ATLAS_DB_USER} password=${ATLAS_DB_PASSWORD} port=${ATLAS_DB_PORT}"
PROCESSING "CLOSE_CONNECTION=DEFER"
EOF

cat > /srv/mapserver/connection_nap.inc <<EOF
CONNECTIONTYPE postgis
CONNECTION "host=${NAP_DB_HOST} dbname=${NAP_DB_NAME} user=${NAP_DB_USER} password=${NAP_DB_PASSWORD} port=${NAP_DB_PORT}"
PROCESSING "CLOSE_CONNECTION=DEFER"
EOF

cat > /srv/mapserver/connection_milieu.inc <<EOF
CONNECTIONTYPE postgis
CONNECTION "host=${MILIEUTHEMAS_DB_HOST} dbname=${MILIEUTHEMAS_DB_NAME} user=${MILIEUTHEMAS_DB_USER} password=${MILIEUTHEMAS_DB_PASSWORD} port=${MILIEUTHEMAS_DB_PORT}"
PROCESSING "CLOSE_CONNECTION=DEFER"
EOF

cat > /srv/mapserver/connection_panorama.inc <<EOF
CONNECTIONTYPE postgis
CONNECTION "host=${PANORAMA_DB_HOST} dbname=${PANORAMA_DB_NAME} user=${PANORAMA_DB_USER} password=${PANORAMA_DB_PASSWORD} port=${PANORAMA_DB_PORT}"
PROCESSING "CLOSE_CONNECTION=DEFER"
EOF

cat > /srv/mapserver/connection_parkeervakken.inc <<EOF
CONNECTIONTYPE postgis
CONNECTION "host=${PARKEERVAKKEN_DB_HOST} dbname=${PARKEERVAKKEN_DB_NAME} user=${PARKEERVAKKEN_DB_USER} password=${PARKEERVAKKEN_DB_PASSWORD} port=${PARKEERVAKKEN_DB_PORT}"
PROCESSING "CLOSE_CONNECTION=DEFER"
EOF

cat > /srv/mapserver/connection_predictiveparking.inc <<EOF
CONNECTIONTYPE postgis
CONNECTION "host=${PREDICTIVEPARKING_DB_HOST} dbname=${PREDICTIVEPARKING_DB_NAME} user=${PREDICTIVEPARKING_DB_USER} password=${PREDICTIVEPARKING_DB_PASSWORD} port=${PREDICTIVEPARKING_DB_PORT}"
PROCESSING "CLOSE_CONNECTION=DEFER"
EOF


cat > /srv/mapserver/connection_basiskaart.inc <<EOF
CONNECTIONTYPE postgis
CONNECTION "host=${BASISKAART_DB_HOST} dbname=${BASISKAART_DB_NAME} user=${BASISKAART_DB_USER} password=${BASISKAART_DB_PASSWORD} port=${BASISKAART_DB_PORT}"
PROCESSING "CLOSE_CONNECTION=DEFER"
EOF

cat > /srv/mapserver/connection_handelsregister.inc <<EOF
CONNECTIONTYPE postgis
CONNECTION "host=${HANDELSREGISTER_DB_HOST} dbname=${HANDELSREGISTER_DB_NAME} user=${HANDELSREGISTER_DB_USER} password=${HANDELSREGISTER_DB_PASSWORD} port=${HANDELSREGISTER_DB_PORT}"
PROCESSING "CLOSE_CONNECTION=DEFER"
EOF

cat > /srv/mapserver/connection_tellus.inc <<EOF
CONNECTIONTYPE postgis
CONNECTION "host=${TELLUS_DB_HOST} dbname=${TELLUS_DB_NAME} user=${TELLUS_DB_USER} password=${TELLUS_DB_PASSWORD} port=${TELLUS_DB_PORT}"
EOF

cat > /srv/mapserver/connection_monumenten.inc <<EOF
CONNECTIONTYPE postgis
CONNECTION "host=${MONUMENTEN_DB_HOST} dbname=${MONUMENTEN_DB_NAME} user=${MONUMENTEN_DB_USER} password=${MONUMENTEN_DB_PASSWORD} port=${MONUMENTEN_DB_PORT}"
EOF

cat > /srv/mapserver/connection_overlastgebieden.inc <<EOF
CONNECTIONTYPE postgis
CONNECTION "host=${OVERLASTGEBIEDEN_DB_HOST} dbname=${OVERLASTGEBIEDEN_DB_NAME} user=${OVERLASTGEBIEDEN_DB_USER} password=${OVERLASTGEBIEDEN_DB_PASSWORD} port=${OVERLASTGEBIEDEN_DB_PORT}"
EOF

# Configure apache to redirect errors to stderr.
# The mapserver will redirect errors to apache errorstream (see header.inc and private/header.inc)
# and apache will then redirect this to stderr, which will then be redirected to syslog/kibana.
# ref: http://mapserver.org/optimization/debugging.html#steps-to-enable-mapserver-debugging
#      https://serverfault.com/questions/711168/writing-apache2-logs-to-stdout-stderr
sed -i 's/ErrorLog .*/ErrorLog \/dev\/stderr/' /etc/apache2/apache2.conf

# Replace actual location of the mapserver depending on the environment
sed -i 's#MAP_URL_REPLACE#'"$MAP_URL"'#g' /srv/mapserver/topografie.map /srv/mapserver/topografie_wm.map

echo Starting server
apachectl -D FOREGROUND

