name: CI

# Run this workflow every time a commit is pushed to main
# The `workflow_dispatch` had been added to be able to run the
# workflow manually (for testing purposes).
on:
  push:
    branches:
      - "main" 
  workflow_dispatch:

jobs:
    build:
        name: Trigger Deploy pipeline on Azure DevOps.
        runs-on: ubuntu-latest
        steps:
        - name: Call Azure
          uses: amsterdam/trigger-ado-pipeline@v1
          with:
            pipeline-id: ${{ secrets.AZURE_DEVOPS_PIPELINE_ID }}
            organisation: ${{ secrets.AZURE_DEVOPS_ORG }}
            project: ${{ secrets.AZURE_DEVOPS_PROJECT }}
            pat-token: ${{ secrets.AZURE_DEVOPS_TOKEN }}
            template-params: '{"environments": "- dev\n- acc\n- prd", "branch": "main", "includeApp": "private", "akscluster": "blue"}'
